# debug = true

# skip_paths = [
#     "todolint.toml",
#     ".git",
#     "i18n",
#     "l10n",
#     "node_modules",
#     "target",
#     "vendor",
# ]

formal_task_pattern = "(?i)^.*pending: [^:]+:.+$"

task_names = [
    "band aid",
    "band-aid",
    "bandaid",
    "bodge",
    "cludge",
    "duct tape",
    "duct-tape",
    "ducttape",
    "duck tape",
    "duck-tape",
    "ducktape",
    "hack",
    "kludge",
    "fixme",
    "jury rig",
    "jury-rig",
    "juryrig",
    "macgyver",
    "makeshift",
    "rube goldberg",
    "rube-goldberg",
    "rube goldberg",
    "stop-gap",
    "stop gap",
    "stopgap",
    "temporary solution",
    "to-do",
    "todo",
    "waiting on",
    "workaround",
]
