# debug = true

# skip_paths = [
#     "todolint.toml",
#     ".git",
#     "i18n",
#     "l10n",
#     "node_modules",
#     "target",
#     "vendor",
# ]

formal_task_pattern = "(?i)^.*pendiente: [^:]+:.+$"

task_names = [
    "pte",
    "pend",
    "pendiente",
    "truco",
]
